version: '2'
services:
  eurekaserver:
    image: goszczyn/eureka-server:v1
    ports:
       - "8761:8761"
    environment:
        EUREKASERVER_URI: "http://${DOCKER_IP}:8761/eureka/"   
        GRAYLOG_HOST: "${DOCKER_IP}"
        GRAYLOG_PORT: "12201"