version: '2'
services:
  configserver:
    image: goszczyn/config-server:v1
    ports:
       - "8888:8888"
    environment:
       EUREKASERVER_URI: "http://${DOCKER_IP}:8761/eureka/"
       EUREKASERVER_PORT: "8761"
       DOCKER_IP: "${DOCKER_IP}"   
       GRAYLOG_HOST: "${DOCKER_IP}"
       GRAYLOG_PORT: "12201"
