version: '2'
services:
  leadservice:
    image: goszczyn/lead-service:v1
    ports:
      - "8080:8080"
    environment:
        PROFILE: "dev"
        SERVER_PORT: "8080"
        EUREKASERVER_PORT:   "8761"
        CONFIGSERVER_PORT:   "8888"
        EUREKASERVER_URI: "http://${DOCKER_IP}:8761/eureka/"
        DOCKER_IP: "${DOCKER_IP}"   
        GRAYLOG_HOST: "${DOCKER_IP}"
        GRAYLOG_PORT: "12201"
