version: '2'
services:
  leadservice:
    image: goszczyn/leadservice:v1
    ports:
      - "8080:8080"
    environment:
        PROFILE: "dev"
        SERVER_PORT: "8080"
        EUREKASERVER_PORT:   "8761"
        CONFIGSERVER_PORT:   "8888"
        EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
