version: '2'
services:
  database:
    image: postgres:9.5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "1qaz2wsx"
      POSTGRES_DB:       "microDB"