version: '2'
services:
  eurekaserver:
    image: goszczyn/eureka-server:v1
    ports:
       - "8761:8761"
    environment:
        EUREKASERVER_URI: "http://192.168.99.102:8761/eureka/"	   
  configserver:
    image: goszczyn/config-server:v1
    ports:
       - "8888:8888"
    environment:
         EUREKASERVER_URI: "http://192.168.99.100:8761/eureka/"
         EUREKASERVER_PORT: "8761"
  zuulserver:
    image: goszczyn/zuul-server:v1
    ports:
      - "5555:5555"
    environment:
      PROFILE: "default"
      SERVER_PORT: "5555"
      CONFIGSERVER_URI: "http://192.168.99.100:8888"
      EUREKASERVER_URI: "http://192.168.99.100:8761/eureka/"
      EUREKASERVER_PORT:        "8761"
      CONFIGSERVER_PORT:        "8888"
  leadservice:
    image: goszczyn/lead-service:v1
    ports:
      - "8080:8080"
    environment:
        PROFILE: "dev"
        SERVER_PORT: "8080"
        EUREKASERVER_PORT:   "8761"
        CONFIGSERVER_PORT:   "8888"
        EUREKASERVER_URI: "http://192.168.99.100:8761/eureka/"