version: '2'
services:
  eurekaserver:
    image: goszczyn/eureka-server:v1
    ports:
       - "8761:8761"
  configserver:
    image: goszczyn/config-server:v1
    ports:
       - "8888:8888"
    environment:
         EUREKASERVER_URI: "http://192.168.99.100:8761/eureka/"
         EUREKASERVER_PORT: "8761"
  leadservice:
    image: goszczyn/leadservice:v1
    ports:
      - "8080:8080"
    environment:
        PROFILE: "dev"
        SERVER_PORT: "8080"
        EUREKASERVER_PORT:   "8761"
        CONFIGSERVER_PORT:   "8888"
        EUREKASERVER_URI: "http://192.168.99.100:8761/eureka/"