version: '2'
services:
  database:
    image: postgres:9.5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "1qaz2wsx"
      POSTGRES_DB:       "microDB"
  eurekaserver:
    image: goszczyn/eureka-server:v1
    ports:
       - "8761:8761"
    environment:
        EUREKASERVER_URI: "http://${DOCKER_IP}:8761/eureka/"   
        GRAYLOG_HOST: "${DOCKER_IP}"
        GRAYLOG_PORT: "12201"
  configserver:
    image: goszczyn/config-server:v1
    ports:
       - "8888:8888"
    environment:
       EUREKASERVER_URI: "http://${DOCKER_IP}:8761/eureka/"
       EUREKASERVER_PORT: "8761"
       DOCKER_IP: "${DOCKER_IP}"   
       GRAYLOG_HOST: "${DOCKER_IP}"
       GRAYLOG_PORT: "12201"
  zuulserver:
    image: goszczyn/zuul-server:v1
    ports:
      - "5555:5555"
    environment:
      EUREKASERVER_URI: "http://${DOCKER_IP}:8761/eureka/"
      EUREKASERVER_PORT: "8761"
      CONFIGSERVER_PORT: "8888"
      DOCKER_IP: "${DOCKER_IP}"   
      GRAYLOG_HOST: "${DOCKER_IP}"
      GRAYLOG_PORT: "12201"
  leadservice:
    image: goszczyn/lead-service:v1
    ports:
      - "8080:8080"
    environment:
        PROFILE: "dev"
        SERVER_PORT: "8080"
        EUREKASERVER_PORT:   "8761"
        CONFIGSERVER_PORT:   "8888"
        EUREKASERVER_URI: "http://${DOCKER_IP}:8761/eureka/"
        DOCKER_IP: "${DOCKER_IP}"   
        GRAYLOG_HOST: "${DOCKER_IP}"
        GRAYLOG_PORT: "12201"
  agentservice:
    image: goszczyn/agent-service:v1
    ports:
      - "8090:8090"
    environment:
        PROFILE: "dev"
        SERVER_PORT: "8090"
        EUREKASERVER_PORT:   "8761"
        CONFIGSERVER_PORT:   "8888"
        EUREKASERVER_URI: "http://${DOCKER_IP}:8761/eureka/"
        DOCKER_IP: "${DOCKER_IP}"   
        GRAYLOG_HOST: "${DOCKER_IP}"
        GRAYLOG_PORT: "12201"