version: '2'
services:
  leadservice:
    image: goszczyn/leadservice:v1
    ports:
      - "8080:8080"
    environment:
      PROFILE: "dev"
      CONFIGSERVER_URI: "http://192.168.99.100:8888"
      CONFIGSERVER_PORT:   "8888"
