server: 
  port: 8888
spring:
  cloud:
    config:
      server:
        encrypt.enabled: false
        git:
          uri: https://github.com/goszczyn/ConfigRepo.git
          searchPaths: config/leadservice
          #username: goszczyn
          #password: 1qaz2wsx
  zipkin: 
    baseUrl: http://192.168.99.100:9411
logging: 
 file: /work/logi/myapplication.log
 level: 
  com.netflix: WARN
  org.springframework.web: DEBUG
  com.thoughtmechanix: DEBUG
  pl.goszczyn: INFO
