server:
  port: 8888
spring:
  cloud:
    config:
      server:
        encrypt:
          enabled: false
        git:
          uri: https://github.com/goszczyn/ConfigRepo.git
          searchPaths: config/leadservice
encrypt:
#  key: IMSYMMETRIC
  key-store:
    location: classpath:/server.jks
    password: passwor123
    alias: cfgserverkey
    secret: 1qaz2wsx
logging:
 file: /work/logs/config-server.log
 level:
  org.springframework.cloud.config: DEBUG
  org.springframework.web: INFO
  pl.goszczyn: INFO
